// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: api/EventService.proto

// protoc ./api/EventService.proto --go_out=./internal/server/grpc/ --go-grpc_out=./internal/server/grpc/

package internalgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEventsReq_Period int32

const (
	GetEventsReq_PERIOD_UNSPECIFIED GetEventsReq_Period = 0
	GetEventsReq_PERIOD_DAY         GetEventsReq_Period = 1
	GetEventsReq_PERIOD_WEEK        GetEventsReq_Period = 2
	GetEventsReq_PERIOD_MONTH       GetEventsReq_Period = 3
)

// Enum value maps for GetEventsReq_Period.
var (
	GetEventsReq_Period_name = map[int32]string{
		0: "PERIOD_UNSPECIFIED",
		1: "PERIOD_DAY",
		2: "PERIOD_WEEK",
		3: "PERIOD_MONTH",
	}
	GetEventsReq_Period_value = map[string]int32{
		"PERIOD_UNSPECIFIED": 0,
		"PERIOD_DAY":         1,
		"PERIOD_WEEK":        2,
		"PERIOD_MONTH":       3,
	}
)

func (x GetEventsReq_Period) Enum() *GetEventsReq_Period {
	p := new(GetEventsReq_Period)
	*p = x
	return p
}

func (x GetEventsReq_Period) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetEventsReq_Period) Descriptor() protoreflect.EnumDescriptor {
	return file_api_EventService_proto_enumTypes[0].Descriptor()
}

func (GetEventsReq_Period) Type() protoreflect.EnumType {
	return &file_api_EventService_proto_enumTypes[0]
}

func (x GetEventsReq_Period) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetEventsReq_Period.Descriptor instead.
func (GetEventsReq_Period) EnumDescriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{7, 0}
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	UserID        string                 `protobuf:"bytes,4,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_EventService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Event) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type CreateEventReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	UserID        string                 `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventReq) Reset() {
	*x = CreateEventReq{}
	mi := &file_api_EventService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventReq) ProtoMessage() {}

func (x *CreateEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventReq.ProtoReflect.Descriptor instead.
func (*CreateEventReq) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEventReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateEventReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type CreateEventResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResp) Reset() {
	*x = CreateEventResp{}
	mi := &file_api_EventService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResp) ProtoMessage() {}

func (x *CreateEventResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResp.ProtoReflect.Descriptor instead.
func (*CreateEventResp) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEventResp) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type UpdateEventReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventReq) Reset() {
	*x = UpdateEventReq{}
	mi := &file_api_EventService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventReq) ProtoMessage() {}

func (x *UpdateEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventReq.ProtoReflect.Descriptor instead.
func (*UpdateEventReq) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateEventReq) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type UpdateEventResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventResp) Reset() {
	*x = UpdateEventResp{}
	mi := &file_api_EventService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventResp) ProtoMessage() {}

func (x *UpdateEventResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventResp.ProtoReflect.Descriptor instead.
func (*UpdateEventResp) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateEventResp) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type DeleteEventReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventReq) Reset() {
	*x = DeleteEventReq{}
	mi := &file_api_EventService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventReq) ProtoMessage() {}

func (x *DeleteEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventReq.ProtoReflect.Descriptor instead.
func (*DeleteEventReq) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteEventReq) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type DeleteEventResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventResp) Reset() {
	*x = DeleteEventResp{}
	mi := &file_api_EventService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventResp) ProtoMessage() {}

func (x *DeleteEventResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventResp.ProtoReflect.Descriptor instead.
func (*DeleteEventResp) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{6}
}

type GetEventsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        GetEventsReq_Period    `protobuf:"varint,1,opt,name=period,proto3,enum=event.GetEventsReq_Period" json:"period,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	Day           int32                  `protobuf:"varint,4,opt,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsReq) Reset() {
	*x = GetEventsReq{}
	mi := &file_api_EventService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsReq) ProtoMessage() {}

func (x *GetEventsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsReq.ProtoReflect.Descriptor instead.
func (*GetEventsReq) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{7}
}

func (x *GetEventsReq) GetPeriod() GetEventsReq_Period {
	if x != nil {
		return x.Period
	}
	return GetEventsReq_PERIOD_UNSPECIFIED
}

func (x *GetEventsReq) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetEventsReq) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *GetEventsReq) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

type GetEventsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsResp) Reset() {
	*x = GetEventsResp{}
	mi := &file_api_EventService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsResp) ProtoMessage() {}

func (x *GetEventsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsResp.ProtoReflect.Descriptor instead.
func (*GetEventsResp) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{8}
}

func (x *GetEventsResp) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_api_EventService_proto protoreflect.FileDescriptor

const file_api_EventService_proto_rawDesc = "" +
	"\n" +
	"\x16api/EventService.proto\x12\x05event\x1a\x1fgoogle/protobuf/timestamp.proto\"u\n" +
	"\x05Event\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12.\n" +
	"\x04date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x16\n" +
	"\x06userID\x18\x04 \x01(\tR\x06userID\">\n" +
	"\x0eCreateEventReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\tR\x06userID\"5\n" +
	"\x0fCreateEventResp\x12\"\n" +
	"\x05event\x18\x01 \x01(\v2\f.event.EventR\x05event\"4\n" +
	"\x0eUpdateEventReq\x12\"\n" +
	"\x05event\x18\x01 \x01(\v2\f.event.EventR\x05event\"5\n" +
	"\x0fUpdateEventResp\x12\"\n" +
	"\x05event\x18\x01 \x01(\v2\f.event.EventR\x05event\" \n" +
	"\x0eDeleteEventReq\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"\x11\n" +
	"\x0fDeleteEventResp\"\xd3\x01\n" +
	"\fGetEventsReq\x122\n" +
	"\x06period\x18\x01 \x01(\x0e2\x1a.event.GetEventsReq.PeriodR\x06period\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x03 \x01(\x05R\x05month\x12\x10\n" +
	"\x03day\x18\x04 \x01(\x05R\x03day\"S\n" +
	"\x06Period\x12\x16\n" +
	"\x12PERIOD_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"PERIOD_DAY\x10\x01\x12\x0f\n" +
	"\vPERIOD_WEEK\x10\x02\x12\x10\n" +
	"\fPERIOD_MONTH\x10\x03\"5\n" +
	"\rGetEventsResp\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.event.EventR\x06events2\x85\x02\n" +
	"\fEventService\x12;\n" +
	"\bAddEvent\x12\x15.event.CreateEventReq\x1a\x16.event.CreateEventResp\"\x00\x12>\n" +
	"\vUpdateEvent\x12\x15.event.UpdateEventReq\x1a\x16.event.UpdateEventResp\"\x00\x12>\n" +
	"\vDeleteEvent\x12\x15.event.DeleteEventReq\x1a\x16.event.DeleteEventResp\"\x00\x128\n" +
	"\tGetEvents\x12\x13.event.GetEventsReq\x1a\x14.event.GetEventsResp\"\x00B\x11Z\x0f./;internalgrpcb\x06proto3"

var (
	file_api_EventService_proto_rawDescOnce sync.Once
	file_api_EventService_proto_rawDescData []byte
)

func file_api_EventService_proto_rawDescGZIP() []byte {
	file_api_EventService_proto_rawDescOnce.Do(func() {
		file_api_EventService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_EventService_proto_rawDesc), len(file_api_EventService_proto_rawDesc)))
	})
	return file_api_EventService_proto_rawDescData
}

var file_api_EventService_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_EventService_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_EventService_proto_goTypes = []any{
	(GetEventsReq_Period)(0),      // 0: event.GetEventsReq.Period
	(*Event)(nil),                 // 1: event.Event
	(*CreateEventReq)(nil),        // 2: event.CreateEventReq
	(*CreateEventResp)(nil),       // 3: event.CreateEventResp
	(*UpdateEventReq)(nil),        // 4: event.UpdateEventReq
	(*UpdateEventResp)(nil),       // 5: event.UpdateEventResp
	(*DeleteEventReq)(nil),        // 6: event.DeleteEventReq
	(*DeleteEventResp)(nil),       // 7: event.DeleteEventResp
	(*GetEventsReq)(nil),          // 8: event.GetEventsReq
	(*GetEventsResp)(nil),         // 9: event.GetEventsResp
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_api_EventService_proto_depIdxs = []int32{
	10, // 0: event.Event.date:type_name -> google.protobuf.Timestamp
	1,  // 1: event.CreateEventResp.event:type_name -> event.Event
	1,  // 2: event.UpdateEventReq.event:type_name -> event.Event
	1,  // 3: event.UpdateEventResp.event:type_name -> event.Event
	0,  // 4: event.GetEventsReq.period:type_name -> event.GetEventsReq.Period
	1,  // 5: event.GetEventsResp.events:type_name -> event.Event
	2,  // 6: event.EventService.AddEvent:input_type -> event.CreateEventReq
	4,  // 7: event.EventService.UpdateEvent:input_type -> event.UpdateEventReq
	6,  // 8: event.EventService.DeleteEvent:input_type -> event.DeleteEventReq
	8,  // 9: event.EventService.GetEvents:input_type -> event.GetEventsReq
	3,  // 10: event.EventService.AddEvent:output_type -> event.CreateEventResp
	5,  // 11: event.EventService.UpdateEvent:output_type -> event.UpdateEventResp
	7,  // 12: event.EventService.DeleteEvent:output_type -> event.DeleteEventResp
	9,  // 13: event.EventService.GetEvents:output_type -> event.GetEventsResp
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_EventService_proto_init() }
func file_api_EventService_proto_init() {
	if File_api_EventService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_EventService_proto_rawDesc), len(file_api_EventService_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_EventService_proto_goTypes,
		DependencyIndexes: file_api_EventService_proto_depIdxs,
		EnumInfos:         file_api_EventService_proto_enumTypes,
		MessageInfos:      file_api_EventService_proto_msgTypes,
	}.Build()
	File_api_EventService_proto = out.File
	file_api_EventService_proto_goTypes = nil
	file_api_EventService_proto_depIdxs = nil
}
